package tripmindai.com.mk.maintripservice.service.AI;

import java.util.Set;
import java.util.Locale;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public final class AiPromptPolicyTerms {

    public static final Set<String> TRAVEL_TERMS = terms(
            "travel", "trip", "vacation", "holiday", "journey", "visit", "go", "fly", "flight",
            "hotel", "stay", "destination", "city", "country", "beach", "museum", "tour",
            "from", "to", "days", "nights", "budget", "people", "traveler", "travellers",
            "patuvanje", "odmor", "let", "avion", "destinacija",
            "grad", "drzava", "drzhava", "dena", "nokji", "budzet", "budzhet",
            "itinerary", "route", "planner", "planning", "schedule", "agenda", "program", "plan",
            "roadtrip", "road trip", "weekend", "break", "escape", "getaway", "tourism", "tourist",
            "sightseeing", "sightsee", "explore", "exploration", "discover", "discovery", "adventure",
            "relax", "relaxation", "family trip", "couple trip", "solo trip", "business trip",
            "honeymoon", "anniversary", "birthday trip", "city break", "short break", "long weekend",
            "summer vacation", "winter vacation", "spring break", "autumn trip", "season", "weather",
            "climate", "temperature", "rain", "sun", "sunny", "snow", "warm", "cold", "forecast",
            "passport", "visa", "insurance", "travel insurance", "documents", "booking", "reservation",
            "check in", "check out", "checkin", "checkout", "arrival", "departure", "return",
            "round trip", "one way", "direct flight", "layover", "stopover", "connection", "transit",
            "airport", "terminal", "gate", "airline", "airlines", "ticket", "tickets", "boarding",
            "boarding pass", "baggage", "luggage", "carry on", "checked bag", "seat", "cabin",
            "economy", "business class", "first class", "train", "bus", "metro", "subway", "tram",
            "taxi", "transfer", "shuttle", "car rental", "rental car", "ferry", "boat", "cruise",
            "accommodation", "lodging", "hostel", "apartment", "villa", "resort", "guesthouse",
            "bnb", "bed breakfast", "room", "rooms", "suite", "breakfast", "half board", "full board",
            "all inclusive", "parking", "pool", "spa", "wifi", "pet friendly", "sea view", "city view",
            "near center", "near beach", "near airport", "downtown", "old town", "neighborhood",
            "landmark", "landmarks", "attraction", "attractions", "monument", "monuments", "gallery",
            "castle", "palace", "cathedral", "church", "mosque", "temple", "ruins", "archaeology",
            "culture", "cultural", "history", "historical", "architecture", "art", "local art",
            "park", "garden", "zoo", "aquarium", "viewpoint", "panorama", "sunset", "sunrise",
            "nature", "hiking", "walk", "walking", "walking route", "trail", "trekking", "cycling",
            "bike", "bicycle", "beaches", "island", "islands", "lake", "river", "mountain",
            "mountains", "forest", "waterfall", "cave", "national park", "scenic", "photo spot",
            "restaurant", "restaurants", "cafe", "bar", "pub", "food", "foodie", "cuisine",
            "local cuisine", "traditional food", "street food", "dinner", "lunch", "brunch", "coffee",
            "dessert", "wine", "winery", "tasting", "market", "bazaar", "shopping", "mall",
            "souvenir", "souvenirs", "nightlife", "club", "concert", "festival", "event", "show",
            "activity", "activities", "experience", "experiences", "excursion", "day trip", "guided tour",
            "free time", "morning", "afternoon", "evening", "night", "midday", "early morning",
            "late night", "duration", "date", "dates", "month", "week", "weeks", "weekday", "weekdays",
            "adults", "adult", "children", "kids", "child", "baby", "infant", "guest", "guests",
            "person", "persons", "group", "couple", "family", "friends", "students", "senior",
            "cheap", "affordable", "luxury", "premium", "midrange", "low budget", "high budget",
            "price", "cost", "currency", "euro", "eur", "usd", "gbp", "mkd", "money", "total price",
            "per person", "per night", "interests", "preferences", "prefer", "include", "exclude",
            "recommend", "recommendation", "suggest", "suggestion", "best", "top", "must see",
            "hidden gem", "local", "safe", "safety", "accessibility", "accessible", "wheelchair",
            "romantic", "quiet", "lively", "relaxed", "fast paced", "slow paced", "kid friendly",
            "budget friendly", "food lover", "nature lover", "history lover", "museum lover",
            "patuvam", "patuvame", "patuva", "pat", "planiraj", "planiram", "planiranje",
            "predlog", "predlozi", "preporaka", "preporacaj", "preporachaj", "itinerer", "ruta",
            "tura", "turizam", "turist", "turisticki", "turistichki", "atrakcija", "atrakcii",
            "znamenitost", "znamenitosti", "muzej", "galerija", "plaza", "plazha", "more", "ezero",
            "planina", "park", "prosetka", "proshetka", "pesacenje", "peshachenje", "restoran",
            "kafe", "bar", "hrana", "kujna", "lokalno", "tradicionalno", "vecera", "vechera",
            "rucek", "ruchek", "dorucek", "doruchek", "soping", "shopping", "nokjen zivot",
            "noken zivot", "smestuvanje", "smestaj", "hotel", "soba", "rezervacija", "aerodrom",
            "aviokompanija", "karta", "bilet", "bagaz", "bagazh", "presednuvanje", "direkten",
            "direkten let", "povraten", "eden pravec", "poagjanje", "poaganje", "pristignuvanje",
            "vrakjanje", "vrakjanje", "datum", "datumi", "denes", "utre", "vikend", "nedela",
            "mesec", "vozrasni", "deca", "gosti", "lica", "pari", "budzetno", "evtino",
            "luksuzno", "cena", "trosok", "troshok", "valuta", "evra", "preporaki"
    );

    public static final Set<String> BLOCKED_TERMS = terms(
            "hack", "hacker", "malware", "exploit", "sql injection", "xss", "password", "bomb",
            "weapon", "drugs", "porn", "sex", "kill", "suicide", "self harm",
            "jailbreak", "prompt injection", "system prompt", "developer prompt", "hidden prompt",
            "initial prompt", "internal prompt", "secret prompt", "ignore instructions", "ignore previous",
            "ignore above", "ignore all", "bypass instructions", "override instructions", "disregard",
            "act as", "pretend to be", "roleplay as", "dan mode", "do anything now", "unfiltered",
            "no restrictions", "no rules", "break rules", "disable safety", "turn off safety",
            "safety bypass", "policy bypass", "content policy", "show policy", "reveal policy",
            "developer message", "system message", "tool message", "chain of thought", "hidden reasoning",
            "private reasoning", "show reasoning", "scratchpad", "internal reasoning", "confidential",
            "secret", "secrets", "api key", "api keys", "apikey", "access token", "refresh token",
            "bearer token", "jwt", "jwt token", "jwt tokens", "session token", "cookie", "cookies", "csrf", "credential",
            "credentials", "login", "admin login", "root password", "database password", "db password",
            "env", "environment variable", "env var", "dotenv", ".env", "private key", "ssh key",
            "rsa key", "pem", "certificate", "vault", "keystore", "connection string", "jdbc url",
            "database url", "azure key", "openai key", "azure openai key", "client secret",
            "client id", "tenant id", "webhook secret", "github token", "git token", "docker secret",
            "dump", "database dump", "export database", "exfiltrate", "exfiltration", "data leak",
            "leak data", "steal data", "steal", "phish", "phishing", "social engineering",
            "credential stuffing", "bruteforce", "brute force", "password spraying", "keylogger",
            "session hijack", "token theft", "cookie theft", "account takeover", "takeover",
            "privilege escalation", "escalate privileges", "root access", "admin access", "backdoor",
            "trojan", "virus", "worm", "ransomware", "spyware", "adware", "botnet", "payload",
            "shellcode", "reverse shell", "bind shell", "meterpreter", "msfvenom", "metasploit",
            "cobalt strike", "beacon", "rat", "remote access trojan", "persistence", "lateral movement",
            "command and control", "c2", "obfuscate malware", "polymorphic", "dropper", "loader",
            "rootkit", "bootkit", "process injection", "dll injection", "code injection",
            "memory injection", "credential dump", "lsass", "mimikatz", "hashdump", "ntlm",
            "pass the hash", "kerberoast", "kerberoasting", "golden ticket", "silver ticket",
            "sqlmap", "nmap", "masscan", "nikto", "burp", "burp suite", "zap", "hydra",
            "john the ripper", "hashcat", "aircrack", "wireshark", "tcpdump", "recon",
            "reconnaissance", "enumeration", "scan ports", "port scan", "vulnerability scan",
            "exploit db", "exploitdb", "cve", "zero day", "0day", "rce", "remote code execution",
            "command injection", "os command", "shell command", "powershell", "cmd.exe", "bash",
            "terminal command", "execute command", "run command", "spawn shell", "download payload",
            "upload shell", "web shell", "php shell", "reverse proxy", "ssrf", "server side request forgery",
            "xxe", "xml external entity", "path traversal", "directory traversal", "../", "..\\",
            "file inclusion", "local file inclusion", "remote file inclusion", "lfi", "rfi",
            "deserialize", "deserialization", "insecure deserialization", "template injection",
            "ssti", "server side template injection", "ldap injection", "xpath injection",
            "nosql injection", "graphql injection", "orm injection", "csrf attack", "clickjacking",
            "open redirect", "cors exploit", "subdomain takeover", "dns rebinding", "cache poisoning",
            "request smuggling", "http smuggling", "host header injection", "log4shell", "spring4shell",
            "deserialization gadget", "ysoserial", "prototype pollution", "npm token", "supply chain attack",
            "dependency confusion", "typosquatting", "malicious package", "shell script", "powershell script",
            "batch script", "delete files", "wipe disk", "format disk", "destroy data", "drop table",
            "truncate table", "delete database", "encrypt files", "decrypt ransom", "bypass login",
            "bypass authentication", "bypass authorization", "disable auth", "disable logging",
            "cover tracks", "clear logs", "delete logs", "evade detection", "antivirus bypass",
            "edr bypass", "firewall bypass", "rate limit bypass", "captcha bypass", "2fa bypass",
            "mfa bypass", "otp bypass", "spoof", "spoofing", "ip spoof", "email spoof",
            "sms bombing", "ddos", "dos attack", "denial of service", "slowloris", "stress test",
            "booter", "stresser", "carding", "credit card", "cvv", "ssn", "passport number",
            "personal data", "pii", "dox", "doxx", "doxxing", "harass", "stalk", "stalking",
            "blackmail", "extort", "extortion", "fraud", "fake id", "forged document", "counterfeit",
            "illegal", "piracy", "crack software", "license key", "serial key", "keygen", "torrent",
            "drug", "cocaine", "heroin", "meth", "fentanyl", "weed dealer", "weapon", "gun",
            "firearm", "knife attack", "explosive", "explosives", "poison", "toxin", "harm someone",
            "hurt someone", "murder", "assassinate", "terrorism", "terrorist", "violent attack",
            "self-harm", "self harm", "harm myself", "end my life", "suicidal", "child sexual",
            "csam", "underage sexual", "non consensual", "revenge porn", "explicit sexual"
    );

    private AiPromptPolicyTerms() {
    }

    private static Set<String> terms(String... values) {
        return Stream.of(values)
                .map(value -> value.toLowerCase(Locale.ROOT).trim())
                .filter(value -> !value.isBlank())
                .collect(Collectors.toUnmodifiableSet());
    }
}
