spring.application.name=main-travel-service

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/TravelMindAIData
spring.datasource.username=postgres
spring.datasource.password=dimo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true